---
app-id: org.jmuelbert.qtwidgettest
runtime: org.kde.Platform
runtime-version: "5.15"
sdk: org.kde.Sdk
command: qtwidgettest
finish-args:
  # X11 + XShm access
  - --share=ipc
  - --socket=x11
  # Wayland access
  - --socket=wayland
  - --device=dri
  # Connectivity
  - --share=network
  # QtSingleApplication, allow other instances to see log files
  - --env=TMPDIR=/var/tmp
  # Allow loading/saving files from anywhere
  - --filesystem=host
  # Notification access
  - --talk-name=org.freedesktop.Notifications
  # System Tray Icon

modules:
  - name: qtwidgettest
    buildsystem: cmake-ninja
    config-opts:
      - -DCMAKE_BUILD_TYPE=Release
      - -DLGTM=ON
    sources:
      - type: dir
        path: ../..
