---
name: Auto approve

# yamllint disable
on:
  pull_request:
    types: [opened, synchronize, reopened]
  # yamllint enable

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v3
        if: github.actor == 'dependabot[bot]'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
