---
name: Missspell fixer

on: [push, pull_request]

jobs:
  misspell-fixer:
    runs-on: ubuntu-latest
    steps:
      - name: "ðŸ§° Checkout"
        uses: actions/checkout@v3

      - name: "Missspell fixer"
        uses: sobolevn/misspell-fixer-action@master

      - name: "Check diff"
        run: git diff --exit-code ${{ github.sha }}

      - name: "Pull Request"
        uses: peter-evans/create-pull-request@v4
        if: failure()
        with:
          commit-message: Fix typos by misspell-fixer
          title: Fix typos by misspell-fixer for ${{ github.ref }}
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}
          branch: auto-pr/misspell-fixer/${{ github.ref }}
